<template>
  <form @submit.prevent="registerUser">
    <input
      type="text"
      id="name"
      placeholder="Name"
      v-model="register.name"
      required
    />
    <button type="submit">Sign in</button>
  </form>
</template>
<script>
export default {
  data() {
    return {
      register: {
        name: "",
        email: "", // optional
        password: "", // optional (will be generated by server)
      },
    };
  },

  created: function () {
    if (localStorage.getItem("jwt") != null) this.$router.replace("/chat");
  },

  methods: {
    async registerUser() {
      try {
        let response = await this.$http.post("/user/register", this.register);
        console.log(response);
        let token = response.data.token;
        if (token) {
          localStorage.setItem("jwt", token);
          this.$router.push(this.$route.query.redirect || "/chat");
        } else {
          this.$swal("Woepsie", "Er ging iets mis!", "error");
        }
      } catch (err) {
        let error = err.response;
        console.log(error);
        this.$swal("Fout", error.data.message, "error");
      }
    },
  },
};
</script>